# Generated by Django 3.2.4 on 2021-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('tag', models.TextField(max_length=200)),
            ],
        ),
    ]
